# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v1
      - name: Create config
        run: |
          printf "{\n\"ENV\": \"development\",\n" > config.json
          printf "\"SECRET_KEY\": \"dev\",\n" >> config.json
          printf "\"HOST\": \"127.0.0.1\",\n" >> config.json
          printf "\"HOST_PORT\": \"127.0.0.1:5000\"}" >> config.json
      - name: Install dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install virtualenv
          /home/runner/.local/bin/virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Run tests
        run: python3 -m pytest
